# RuinsCore Standardkonfiguration
# Diese Datei wird beim ersten Start nach plugins/RuinsCore/config.yml kopiert.

database:
  file: ruinscore.db

loader:
  command-package: de.satsuya.ruinsCore.commands
  listener-package: de.satsuya.ruinsCore.listeners

alerts:
  prefix: "[StaffAlert]"

jobs:
  holzfaeller:
    restrictions:
      paralysis-ticks: 80
      plank-drop-chance: 0.35
  bauer:
    restrictions:
      deny-plant-message: "§cNur Bauer dürfen Nahrungspflanzen anbauen."
      deny-harvest-message: "§cNur Bauer dürfen Nahrungspflanzen abbauen."
      deny-craft-message: "§cNur Bauer dürfen Essen craften."

